# Bun configuration for React Native/Expo project

[install]
cache = true
frozen = false

# React Native specific optimizations
[install.scopes]
"@react-native" = { registry = "https://registry.npmjs.org/" }
"@expo" = { registry = "https://registry.npmjs.org/" }

# Performance optimizations
[test]
preload = ["./nativewind-env.d.ts"] 